version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Sa123456"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - local-dev-app

networks:
  local-dev-app: